[asd]
version = "1.0"
generated = true

[module]
name = "counter"
top = "counter"
type = "rtl"

[module.sources]
modules = [
    "examples/counter/rtl/counter.sv",
]

[parameters.WIDTH]
default = 8
wide = 16
narrow = 4

[tools.simulation]
tests = ["examples/counter/sim/sim_counter.py"]

[tools.lint]
